"""therds  migrations

Revision ID: 15b3f6d19950
Revises: c68ca4b9ee88
Create Date: 2022-12-19 17:33:30.982620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b3f6d19950'
down_revision = 'c68ca4b9ee88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
