"""Initial migrations

Revision ID: 181871fb93cc
Revises: 
Create Date: 2022-12-19 17:20:08.123755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181871fb93cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
