"""Added initial table

Revision ID: 1ad6d818c353
Revises: 3e4e5d238eda
Create Date: 2022-12-19 17:43:12.497655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad6d818c353'
down_revision = '3e4e5d238eda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
