"""Added first table

Revision ID: 33b392d6e556
Revises: 1ad6d818c353
Create Date: 2022-12-19 17:44:30.914782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b392d6e556'
down_revision = '1ad6d818c353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('admin', 'student', 'consultor', name='roletype'), server_default='student', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('final_work', 'inscriptions', 'income_25', 'others', name='category'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'in_progress', 'terminated', name='state'), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_table('replys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consult_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consult_id'], ['consults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replys')
    op.drop_table('consults')
    op.drop_table('users')
    # ### end Alembic commands ###
