"""second  migrations

Revision ID: c68ca4b9ee88
Revises: 181871fb93cc
Create Date: 2022-12-19 17:29:17.679748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68ca4b9ee88'
down_revision = '181871fb93cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
